version: '3.5'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - mbw-network
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/mbw
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - ROOT_URL=http://mbw.localhost
      - VIRTUAL_HOST=mbw.localhost
    networks:
      - mbw_proxy-network
      - mbw-network
networks:
  mbw_proxy-network:
    name: mbw_proxy-network
  mbw-network:
    name: mbw-network
  default:
    external:
      name: mbw_proxy-network